# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    # Builds wiz for each architecture
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/tim15/wiz
    steps:
      - checkout
      - run: go get -t -v ./...
      - run: ./test.sh
      - run: bash <(curl -s https://codecov.io/bash)
