// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/install.proto

package install

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PackageRequest_Command int32

const (
	PackageRequest_INSTALL PackageRequest_Command = 0
	PackageRequest_DELETE  PackageRequest_Command = 1
)

var PackageRequest_Command_name = map[int32]string{
	0: "INSTALL",
	1: "DELETE",
}

var PackageRequest_Command_value = map[string]int32{
	"INSTALL": 0,
	"DELETE":  1,
}

func (x PackageRequest_Command) String() string {
	return proto.EnumName(PackageRequest_Command_name, int32(x))
}

func (PackageRequest_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33aa0c3c5178ec69, []int{1, 0}
}

// Basic definition of a package - unique and constant name, unique version
// Can use hash instead
type MinPackageSpec struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinPackageSpec) Reset()         { *m = MinPackageSpec{} }
func (m *MinPackageSpec) String() string { return proto.CompactTextString(m) }
func (*MinPackageSpec) ProtoMessage()    {}
func (*MinPackageSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_33aa0c3c5178ec69, []int{0}
}

func (m *MinPackageSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinPackageSpec.Unmarshal(m, b)
}
func (m *MinPackageSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinPackageSpec.Marshal(b, m, deterministic)
}
func (m *MinPackageSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinPackageSpec.Merge(m, src)
}
func (m *MinPackageSpec) XXX_Size() int {
	return xxx_messageInfo_MinPackageSpec.Size(m)
}
func (m *MinPackageSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_MinPackageSpec.DiscardUnknown(m)
}

var xxx_messageInfo_MinPackageSpec proto.InternalMessageInfo

func (m *MinPackageSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MinPackageSpec) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Two basic package management commands, install and delete
// These are deterministic actions on the store
type PackageRequest struct {
	// Types that are valid to be assigned to Package:
	//	*PackageRequest_Spec
	//	*PackageRequest_PackageHash
	Package              isPackageRequest_Package `protobuf_oneof:"package"`
	Store                string                   `protobuf:"bytes,2,opt,name=store,proto3" json:"store,omitempty"`
	Command              PackageRequest_Command   `protobuf:"varint,3,opt,name=command,proto3,enum=commands.PackageRequest_Command" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PackageRequest) Reset()         { *m = PackageRequest{} }
func (m *PackageRequest) String() string { return proto.CompactTextString(m) }
func (*PackageRequest) ProtoMessage()    {}
func (*PackageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33aa0c3c5178ec69, []int{1}
}

func (m *PackageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageRequest.Unmarshal(m, b)
}
func (m *PackageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageRequest.Marshal(b, m, deterministic)
}
func (m *PackageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRequest.Merge(m, src)
}
func (m *PackageRequest) XXX_Size() int {
	return xxx_messageInfo_PackageRequest.Size(m)
}
func (m *PackageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRequest proto.InternalMessageInfo

type isPackageRequest_Package interface {
	isPackageRequest_Package()
}

type PackageRequest_Spec struct {
	Spec *MinPackageSpec `protobuf:"bytes,1,opt,name=spec,proto3,oneof"`
}

type PackageRequest_PackageHash struct {
	PackageHash string `protobuf:"bytes,4,opt,name=package_hash,json=packageHash,proto3,oneof"`
}

func (*PackageRequest_Spec) isPackageRequest_Package() {}

func (*PackageRequest_PackageHash) isPackageRequest_Package() {}

func (m *PackageRequest) GetPackage() isPackageRequest_Package {
	if m != nil {
		return m.Package
	}
	return nil
}

func (m *PackageRequest) GetSpec() *MinPackageSpec {
	if x, ok := m.GetPackage().(*PackageRequest_Spec); ok {
		return x.Spec
	}
	return nil
}

func (m *PackageRequest) GetPackageHash() string {
	if x, ok := m.GetPackage().(*PackageRequest_PackageHash); ok {
		return x.PackageHash
	}
	return ""
}

func (m *PackageRequest) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *PackageRequest) GetCommand() PackageRequest_Command {
	if m != nil {
		return m.Command
	}
	return PackageRequest_INSTALL
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PackageRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PackageRequest_OneofMarshaler, _PackageRequest_OneofUnmarshaler, _PackageRequest_OneofSizer, []interface{}{
		(*PackageRequest_Spec)(nil),
		(*PackageRequest_PackageHash)(nil),
	}
}

func _PackageRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PackageRequest)
	// package
	switch x := m.Package.(type) {
	case *PackageRequest_Spec:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Spec); err != nil {
			return err
		}
	case *PackageRequest_PackageHash:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.PackageHash)
	case nil:
	default:
		return fmt.Errorf("PackageRequest.Package has unexpected type %T", x)
	}
	return nil
}

func _PackageRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PackageRequest)
	switch tag {
	case 1: // package.spec
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MinPackageSpec)
		err := b.DecodeMessage(msg)
		m.Package = &PackageRequest_Spec{msg}
		return true, err
	case 4: // package.package_hash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Package = &PackageRequest_PackageHash{x}
		return true, err
	default:
		return false, nil
	}
}

func _PackageRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PackageRequest)
	// package
	switch x := m.Package.(type) {
	case *PackageRequest_Spec:
		s := proto.Size(x.Spec)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PackageRequest_PackageHash:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.PackageHash)))
		n += len(x.PackageHash)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PackagesRequest struct {
	PackageRequest       []*PackageRequest `protobuf:"bytes,1,rep,name=package_request,json=packageRequest,proto3" json:"package_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PackagesRequest) Reset()         { *m = PackagesRequest{} }
func (m *PackagesRequest) String() string { return proto.CompactTextString(m) }
func (*PackagesRequest) ProtoMessage()    {}
func (*PackagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33aa0c3c5178ec69, []int{2}
}

func (m *PackagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackagesRequest.Unmarshal(m, b)
}
func (m *PackagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackagesRequest.Marshal(b, m, deterministic)
}
func (m *PackagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackagesRequest.Merge(m, src)
}
func (m *PackagesRequest) XXX_Size() int {
	return xxx_messageInfo_PackagesRequest.Size(m)
}
func (m *PackagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PackagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PackagesRequest proto.InternalMessageInfo

func (m *PackagesRequest) GetPackageRequest() []*PackageRequest {
	if m != nil {
		return m.PackageRequest
	}
	return nil
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_33aa0c3c5178ec69, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("commands.PackageRequest_Command", PackageRequest_Command_name, PackageRequest_Command_value)
	proto.RegisterType((*MinPackageSpec)(nil), "commands.MinPackageSpec")
	proto.RegisterType((*PackageRequest)(nil), "commands.PackageRequest")
	proto.RegisterType((*PackagesRequest)(nil), "commands.PackagesRequest")
	proto.RegisterType((*Error)(nil), "commands.Error")
}

func init() { proto.RegisterFile("src/proto/install.proto", fileDescriptor_33aa0c3c5178ec69) }

var fileDescriptor_33aa0c3c5178ec69 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x6d, 0x7e, 0xfd, 0x93, 0x76, 0xfa, 0x23, 0x2d, 0x8b, 0xe0, 0xea, 0x29, 0x46, 0x90, 0x9e,
	0x12, 0xa8, 0x7a, 0xf1, 0x20, 0xb4, 0x36, 0xd0, 0x42, 0x15, 0x49, 0x7b, 0xf2, 0x22, 0xdb, 0x74,
	0x49, 0x42, 0x9b, 0x64, 0xdd, 0x4d, 0x2d, 0xf8, 0x81, 0xfd, 0x1c, 0x92, 0xec, 0x2e, 0x25, 0x78,
	0xf2, 0x94, 0xbc, 0x37, 0x99, 0xf7, 0xde, 0x4c, 0x06, 0xce, 0x05, 0x0f, 0x3d, 0xc6, 0xf3, 0x22,
	0xf7, 0x92, 0x4c, 0x14, 0x64, 0xbf, 0x77, 0x2b, 0x84, 0xba, 0x61, 0x9e, 0xa6, 0x24, 0xdb, 0x0a,
	0xe7, 0x11, 0xac, 0xe7, 0x24, 0x7b, 0x25, 0xe1, 0x8e, 0x44, 0x74, 0xc5, 0x68, 0x88, 0x10, 0xb4,
	0x32, 0x92, 0x52, 0x6c, 0xd8, 0xc6, 0xa8, 0x17, 0x54, 0xef, 0x08, 0x83, 0xf9, 0x49, 0xb9, 0x48,
	0xf2, 0x0c, 0xff, 0xab, 0x68, 0x0d, 0x9d, 0x6f, 0x03, 0x2c, 0xd5, 0x1d, 0xd0, 0x8f, 0x03, 0x15,
	0x05, 0x72, 0xa1, 0x25, 0x18, 0x0d, 0x2b, 0x81, 0xfe, 0x18, 0xbb, 0xda, 0xcb, 0xad, 0x1b, 0xcd,
	0x1b, 0x41, 0xf5, 0x1d, 0xba, 0x86, 0xff, 0x4c, 0xd2, 0xef, 0x31, 0x11, 0x31, 0x6e, 0x95, 0x0e,
	0xf3, 0x46, 0xd0, 0x57, 0xec, 0x9c, 0x88, 0x18, 0x9d, 0x41, 0x5b, 0x14, 0x39, 0xa7, 0xca, 0x5f,
	0x02, 0xf4, 0x00, 0xa6, 0x52, 0xc7, 0x4d, 0xdb, 0x18, 0x59, 0x63, 0xfb, 0xe4, 0x56, 0x4f, 0xe5,
	0x3e, 0x49, 0x3e, 0xd0, 0x0d, 0x8e, 0x03, 0xa6, 0xe2, 0x50, 0x1f, 0xcc, 0xc5, 0xcb, 0x6a, 0x3d,
	0x59, 0x2e, 0x87, 0x0d, 0x04, 0xd0, 0x99, 0xf9, 0x4b, 0x7f, 0xed, 0x0f, 0x8d, 0x69, 0x0f, 0x4c,
	0x15, 0xc2, 0x59, 0xc3, 0x40, 0x29, 0x0a, 0x3d, 0xe8, 0x04, 0x06, 0x3a, 0x38, 0x97, 0x14, 0x36,
	0xec, 0x66, 0x7d, 0xe6, 0x7a, 0x8a, 0xc0, 0x62, 0x35, 0xec, 0x5c, 0x41, 0xdb, 0xe7, 0x3c, 0xe7,
	0xe5, 0x86, 0x53, 0x2a, 0x04, 0x89, 0xf4, 0xe2, 0x35, 0x1c, 0x1f, 0xa1, 0xab, 0x8d, 0xd1, 0x3d,
	0x98, 0x0b, 0xf9, 0x23, 0xd1, 0xc5, 0x2f, 0x0f, 0x9d, 0xeb, 0x72, 0x70, 0x2a, 0x49, 0xf1, 0x3b,
	0xe8, 0xcc, 0xe8, 0x9e, 0x16, 0xf4, 0x2f, 0x5d, 0xd3, 0xd1, 0xdb, 0x4d, 0x94, 0x14, 0xf1, 0x61,
	0x53, 0x16, 0xbc, 0x63, 0xf2, 0xc5, 0x76, 0x51, 0xf9, 0xd8, 0x7a, 0xe5, 0x59, 0x11, 0x96, 0xe8,
	0xa3, 0xda, 0x74, 0xaa, 0xab, 0xba, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xf9, 0x2a, 0xd3,
	0x70, 0x02, 0x00, 0x00,
}
